services:
  db:
    image: postgres:13.10
    container_name: taski_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - taski_network
    ports:
      - "5432:5432"

  backend:
    image: nikita.polishchuk/taski_backend:latest
    container_name: taski_backend_container
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
    networks:
      - taski_network

  frontend:
    image: nikitapolishchuk/taski_frontend:latest
    container_name: taski_frontend_container
    ports:
      - "8001:8000"
    volumes:
      - static_volume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    networks:
      - taski_network

  nginx:
    image: nikitapolishchuk/taski_nginx:latest
    container_name: taski_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/staticfiles/
    depends_on:
      - backend
      - frontend
    networks:
      - taski_network

volumes:
  pg_data:
  static_volume:

networks:
  taski_network:
    driver: bridge

